### PR TITLE
Use horizontal transitions for the release page

### PR DESCRIPTION
**Pull request by jpnurmi**
[firmware-updater-page-transitions.webm](https://user-images.githubusercontent.com/140617/191685277-97e58b6e-123b-447c-954d-bea78fe433bd.webm)

### CODE REVIEW

**Comment by jpnurmi** [comment]
@d-loose How do you like this? I have mixed feelings. A visual distinction between master vs. detail navigation is great and a horizontal slide feels natural for the "<" back button. On the other hand, the slide does not fit as well with the _Cancel_ and _Upgrade_ buttons.

**Comment by jpnurmi** [comment]
@Feichtmeier any thoughts? :)

**Comment by Feichtmeier** [comment]
I think it looks great!

*( super off-topic-may-be-an-issue: But looking at this multiple times I wonder if the buttons shouldn't all be placed at the top because the mouse travel is increased a lot when they switch from top to button )*

**Comment by jpnurmi** [comment]
Cheers :)

> _( super off-topic-may-be-an-issue: But looking at this multiple times I wonder if the buttons shouldn't all be placed at the top because the mouse travel is increased a lot when they switch from top to bottom )_

I was planning to propose to Elio that we'd move all buttons down. Device and vendor names can be long so having multiple buttons in the same row is problematic on lower resolution screens.

**Comment by d-loose** [comment]
I think it's a great idea to have different animations for different levels of navigation - the sideways transition makes it clearer to the user that it's a nested view.
@Feichtmeier I completely agree, the position of the buttons should be more consistent and the user shouldn't have to chase them across the screen.

**Review by d-loose — APPROVED** [review]
:+1:

**Pull request merged**
