### PR TITLE
feat(device_page): update UI

### PR DESCRIPTION
**Pull request by d-loose**
Ref #177 
UDENG-703

* Moved the buttons around and adjusted labels
* Added 'Update to Latest' button
* Added 'Latest Version' (still a bit tentative, since releases provided by are not guaranteed to be sorted, but are sorted in practice 99.99% of the time)
* Changed 'All Versions' button style from 'Outlined' to 'Filled'
* Added 'Update Available' chip

|Light|Dark|
|-|-|
|Screenshot from 2023-06-29 14-13-34|Screenshot from 2023-06-29 14-13-26|

### CODE REVIEW

**Comment by d-loose** [comment]
Issues I still see:
* 'Checksum' buttons need a lot of horizontal space and get stacked vertically with the current default window size
* Progress bar + status messages move some of the other UI elements around

**Comment by jpnurmi** [comment]
Due to some M3 tweaks in Flutter 3.10, horizontal button padding was increased from 16px to 24px. The padding has been restored back to 16px in yaru.dart 0.8.0 which can be used as a compatible version of yaru_widgets has been released.

**Review by elioqoshi — CHANGES_REQUESTED** [review]
Buttons looks okay, though I am wondering if they can be less tall? ![grafik]

Also, is the modal ready for review yet? We are still using the "Upgrade" wording there (https://github.com/canonical/firmware-updater/assets/5436686/1f170cc8-fd73-4ab6-b4ff-ed2f3833b776)

**Review by jpnurmi — APPROVED** [review]
Implementation LGTM :+1:

**Comment by elioqoshi** [comment]
Nevermind the buttons then good to go!

**Pull request merged**
