### PR TITLE
add upower to access battery state

### PR DESCRIPTION
**Pull request by d-loose**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Needs rebase, otherwise LGTM :+1:

**Comment by d-loose** [comment]
I've added an `onBattery` property to both `FirmwareModel` and `DeviceModel` for now. Thanks to #84 we can probably clean up a bit and remove some redundant things from `FirmwareModel`.

**Comment by jpnurmi** [comment]
Do we need on-battery change notifications to be able to update the GUI?

**Comment by d-loose** [comment]
I'd like to avoid that and rather show the user the same UI regardless of the battery state. There should only be a modified confirmation dialog before installing an update that warns the user if they're on battery. It's probably better to discuss this in #56.
In this case we wouldn't need `onBattery` in `FirmwareModel`.

**Review by jpnurmi — APPROVED** [review]
Ok! :+1:

**Pull request merged**
